import pygame
import sys
import os.path as osp

# const
CONST = {}
CONST['PEDAL_NUM'] = 5
CONST['PEDAL_HEIGHT'] = 14
CONST['PEDAL_WIDTH'] = 68
CONST['BOUNCE_VELOCITY'] = 10

CONST['GRAVITY'] = 0.2

CONST['DOODLE_HEIGHT'] = 70
CONST['DOODLE_WIDTH'] = 51
CONST['DOODLE_X0'] = 100
CONST['DOODLE_Y0'] = 100
CONST['DOODLE_Y_LIMIT'] = 222

CONST['SCREEN_WIDTH'] = 400
CONST['SCREEN_HEIGHT'] = 600

CONST['FPS'] = 120
